---
# VMware Photon OS specific tasks.

# Tasks to update the operating system and install additional packages.
- block:
  - name: "Getting guest operating system information."
    debug:
      msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

  - name: "Updating the operating system."
    command: "tdnf -y update"
    when: ansible_distribution_version | int >= 5

  - block:
    - name: "Updating the repository URL."
      shell: |
        cd /etc/yum.repos.d/
        sed -i 's/dl.bintray.com\/vmware/packages.vmware.com\/photon\/$releasever/g' photon.repo photon-updates.repo photon-extras.repo photon-debuginfo.repo

    - name: "Updating the photon-repos."
      command: tdnf -y update photon-repos

    - name: "Cleaning the cache."
      command: tdnf clean all

    - name: "Making cache."
      command: tdnf makecache

    - name: "Updating the operating system."
      command: tdnf -y update
    when: ansible_distribution_version | int <= 4

  - name: "Installing additional packages."
    command: "tdnf -y install {{ additional_packages[ansible_os_family] | join(' ') }}"

  - name: "Installing cloud-init."
    command: tdnf -y install cloud-init
    when: enable_cloudinit == 'true'
