---
# SUSE Linux Enterprise Server specific tasks.

# Tasks for disconnecting from SUSE Customer Center.
- name: "Disconnecting from SUSE Customer Center."
  command:
    cmd: "{{ item }}"
  loop:
    - SUSEConnect -d
    - SUSEConnect --cleanup

# Tasks for configuring SSH for public key authentication.
- name: "Configuring SSH for Public Key Authentication."
  block:
    - lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
    - lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'

# Tasks for setting the hostname.
- name: "Setting the hostname."
  hostname:
    name: "localhost"

# Tasks for restarting the SSH daemon.
- name: "Restarting the SSH daemon."
  systemd:
    name: sshd
    state: restarted
    daemon_reload: true

# Tasks for configuring cloud-init.
- name: "Configuring cloud-init."
  block:
    - name: "Message: Configuring cloud-init"
      debug:
        msg: "Configuring cloud-init"
    - blockinfile:
        path: /etc/cloud/cloud.cfg
        block: |
          disable_vmware_customization: false
    - copy:
        content: "datasource_list: [ VMware, OVF, None ]"
        dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
  when: enable_cloudinit == 'true'

- name: "Enable the cloud-init daemon."
  systemd:
    name: cloud-init
    state: started
    enabled: yes
    daemon_reload: yes
  when: enable_cloudinit == 'true'
