---
- name: "{{ task_name }}"
  include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat', 'Suse']

- name: "{{ task_name }}"
  include_tasks: "{{ ansible_lsb.codename | lower }}.yml"
  when: ansible_distribution == 'VMware Photon OS'
